name: CI Pipeline
on: [push, pull_request]

jobs:
    ruff:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v6.0.1
              with:
                # Value already defaults to true, but `persist-credentials` is required to push new commits to the repository.
                persist-credentials: true
            # Set up Python
            - name: Set up Python
              uses: actions/setup-python@v6.2.0
              with:
                python-version: "3.13"            
            - name: Install uv and ruff
              run: |
                python -m pip install -U pip uv && \
                  uv pip install ruff mypy --system
            - name: Format with Ruff
              run: uv run ruff format .
            - name: Lint with Ruff
              run: uv run ruff check --fix --output-format=github .            
            - name: Check for changes
              id: changes
              run: |
                if git diff --quiet; then
                  echo "changed=false" >> "$GITHUB_OUTPUT"
                else
                  echo "changed=true" >> "$GITHUB_OUTPUT"
                fi
            - name: Git Auto Commit   
              if: ${{ github.event_name == 'push' && steps.changes.outputs.changed == 'true' }}                         
              uses: stefanzweifel/git-auto-commit-action@v7.1.0
              with:
                commit_message: "style: auto-fix lint/format issues" 
            - name: Add PR comment on Update
              if: ${{ github.event_name == 'pull_request' && steps.changes.outputs.changed == 'true' }}
              uses: mshick/add-pr-comment@v2
              with:
                message: |
                  **Ruff auto-fix with lint/format has been done, please perform git pull --rebase locally**          
            - name: Run mypy with annotations
              run: |
                echo '::add-matcher::.github/mypy-matcher.json'
                uv run mypy --show-error-codes --show-column-numbers src
                echo '::remove-matcher owner=mypy::'